pretrained_model_path: "stable-diffusion-v1-5"
pretrained_vae_path: "sd-vae-ft-mse"
pretrained_controlnet_path: "MagicAnimate/densepose_controlnet"
pretrained_appearance_encoder_path: "MagicAnimate/appearance_encoder"
pretrained_unet_path: ""

motion_module: "MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5


inference_config: "configs/inference/inference.yaml"
size: 512
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false
